CXX?=g++ 
CXXFLAGS+= --std=c++17 -O3 -Wall -Wextra -I.
SOURCES=src/main.cpp src/rectangular.cpp

src/%.o: src/%.cpp 
	$(CXX) $(CXXFLAGS) -c -o $@ $<

rectangular: $(SOURCES:.cpp=.o)
	$(CXX) $(CXXFLAGS) -o $@ $^
